const TestimonialApi = [
    {
      id: 1,
      image: "./image/slide1.png",
      design: "NCD - DESIGN",
      name: "Mevine Thoda",
      offcer: "Marketing Officer",
      post: "CEO - Marketing",
      date: "Via Upwork - Mar 4, 2018 - Jan 30, 2021",
      desc: "his services were up to marked",
    },
    {
      id: 2,
      image: "./image/slide2.png",
      design: "Default name",
      name: "Davei Luace",
      offcer: "Chief Operating Manager",
      post: "Android App Development",
      date: "via Upwork - Mar 4, 2015 - oct 23, 2020",
      desc: "When managment is so important.he manage the project great.",
    },
    {
      id: 3,
      image: "./image/slide3.png",
      design: "Rainbow-Themes",
      name: "Nevine Acotanza",
      offcer: "Chief Operating Officer",
      post: "Android App Development",
      date: "via Upwork - Mar 4, 2021- Aug 30, 2021",
      desc: "Apllication was according to the requirements",
    },
    {
      id: 4,
      image: "./image/slide4.png",
      design: "Bound - Trolola",
      name: "Jone Duone Joe",
      offcer: "Operating Officer",
      post: "Web App Development",
      date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
      desc: "Important fact to see the website because it was more than my expected ",
    },
    {
      id: 5,
      image: "./image/slide5.png",
      design: "Glassfisom",
      name: "Nevine Dhawan",
      offcer: "CEO Of Officer",
      post: "Android App Design",
      date: "Fiver - may 4, 2022 - july 10, 2022",
      desc: "No more question for design. Brilliant design concept used by him.",
    },
  ]
  
  export default TestimonialApi